# Generated by Django 4.1.6 on 2023-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
