# Generated by Django 4.1.6 on 2023-02-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_message_options_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
